=== mikallok/xml-project/phraxis.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="CaseReportForm">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="subtitle" type="xsd:string"/>
            <xsd:element name="case" type="xsd:string"/>
            <xsd:pattern name="PatientID" value="[0-9]\-[01-99]"/>
            <xsd:element name="section" type="xsd:string"/>
            <xsd:element name="gender" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Male"/>
                           <xsd:enumeration value="Female"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="dob" type="xsd:date"/>
            <xsd:element name="age" type="xsd:decimal"/>
            <xsd:element name="height" type="xsd:decimal"/>
            <xsd:element name="height" type="xsd:decimal"/>
            <xsd:element name="gender" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Caucasian"/>
                           <xsd:enumeration value="Black"/>
                           <xsd:enumeration value="Asian"/>
                           <xsd:enumeration value="Hispanic"/>
                           <xsd:enumeration value="Other"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question1" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question2" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question3" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question4" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question5" type="xsd:decimal"/>
            <xsd:element name="Question6" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question7" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration value="Yes"/>
                           <xsd:enumeration value="No"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="Question7" maxOccurs="choice">
               <xsd:complexType mixed="true">
                  <xsd:attribute name="type" use="required">
                     <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:enumeration type="xsd:date"/>
                           <xsd:enumeration value="Unknown"/>
                           <xsd:enumeration value="NA"/>
                        </xsd:restriction>
                     </xsd:simpleType>
                  </xsd:attribute>
               </xsd:complexType>
            </xsd:element>
              <xsd:element name="Question8" type="xsd:decimal"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== mikallok/xml-project/phraxis.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="phraxis_style.css"?>
<CaseReportForm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="phraxis.xsd">


  <title>InterGraft Study:</title>
  <subtitle>Baseline Demography and Clinical History Form</subtitle>
  <case>
  <PatientID>1-01</PatientID>
  <section>Part I. Demographics
	<gender>Male</gender>
	<dob>1952-06-02</dob>
  	<age>65</age>
  	<height>170</height>
  	<weight>136</weight>
  	<ethnicity>Other</ethnicity>
  </section>
  <section>Part II. Dialysis History
  	<Question1>Unknown</Question1>
  	<Question2>NA</Question2>
  	<Question3>Yes</Question3>
  	<Question4>Yes</Question4>
  	<Question5>9</Question5>
  	<Question6>No</Question6>
  	<Question7>No</Question7>
  	<Question8>2017-10-15</Question8>
  	<Question9>1</Question9>
   </section>
</case>
<case>
<PatientID>1-02</PatientID>
<section>Part I. Demographics
<gender>Female</gender>
<dob>1970-09-16</dob>
<age>47</age>
<height>160</height>
<weight>122</weight>
<ethnicity>Asian</ethnicity>
</section>
<section>Part II. Dialysis History
	<Question1>Yes</Question1>
	<Question2>No</Question2>
	<Question3>No</Question3>
	<Question4>Yes</Question4>
	<Question5>30</Question5>
	<Question6>No</Question6>
	<Question7>Yes</Question7>
	<Question8>2017-10-20</Question8>
	<Question9>0</Question9>
</section>
</case>
</CaseReportForm>
